---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: alertmanager-config
  namespace: monitoring
spec:
  encryptedData:
    alertmanager-config.yaml: AgCTuWK2sjaGeh5+x/eE3mwvmZVcDHNJ6p7bEvERYw16ENH/XbjJok0Exp1l2vrGCgsPndIj7y4J+sfEFb4cTaDJ7Z5vB5YTKFJIlvstKFtZ5g4MxvhbG87NajNcuiaWphg//6yjQ/Ojo98znqB6i6JS8EyeSOWRSuNFnS2UTe9snN0ATGHM7WasruC3zmqwkzndmOU0gzAa6aWZRzMHPFoTuMInpYHpZqs7SATSkYIIVFc55fZNLm5mL/9XWeh6kbb4CXbuqtdLwCSQ1PWWrxvNM4FSoyv4IS95aa61sdDrJYvfdq2TNB87kXfTT54KmUHhmucotw7Raf3tRhLaG64XO94P8S8rZYS91O9Uw70a8VlWbyYdFiIiwfjvnEDganjE4FisYrFjWvsKeZzGbNcU5ziGAYq+T5zbfJmKxijwlIrvMBZU1QwgQOwzwZmmPLyWz3pcNDsNdyqvDW6JoRPbc73WDubQHOJR595T1bO6EGcelUKNkUl/xMIZF3ckGg+s1VGdAfy9o5tt8wHHCI27pMLNjHquzsDgYelNuiR5foKX5tCBb23xVxkv2kRXbzGiCAln0ELaSl8zY9kX1O5SHyMaTYM9KEeucok9FQCGBjEOT7ErDPKQlsZH7C5eaiZZI5OoQjALfFxbbjhUlvxaPcf4JHKPFnnlrEa6JJzE5TXmvA34OqTKhSznlt74ahQrOGb1UULEnoqLm2fE3Z3xZbOQXv5wtGmbYHGHNmCa5WFqp+oIp3xSi1qQb5buYAd8CGPnQ1iaInsBfplmjI7shUUkMHS/jUhKtTerxPnssc0fMPi6s8mFHFinnwk5eBucvVnKQnQtv42rJIHmcWXnAe0MR/BtVFjmZretTg5X71dLLjbEX/PD+kOzlRr7LAG/DSSrVPu6DQ7Ey87uBbMomWF7gFWWQkIxpHHKeDc1HlYkjuISKvaPyPqJcjyovJ3LvlwnD+ZD5pO56R7QSgY7IKk3cQGgSgqUmzaqEY4+VM/9pfbkoIziRortHUkHfyrMWk4dYXUqUSsyHPWgmJ/7Xczt093+IkrRvXhe16n+WnCFsYMP2tHPFw4L/sO+YdTvLxhFHVyNB2ApzbIxi1VOWmRrvpJmkHHBSln1vzPLvEOBZLL/LsUnmRmKCUm8n0bdQ5fY6xvsO8SPvZF5k4So5ygcxwkbsWQtR/S0Ty0RSDsP7DRq4zL/7noomqTLZ3MdZKS2+qF0sFJt2OipDujLrfMJW3iImWAYfYgpfaXEXWF2Yg1//KW84KrgF8eMR3B9qwzg5ovQcH7IaDQsa7c/qdiq7T9xW6O62nbry4FIELrTzlBl/Dil6UkbhH+jtCWHqeU1e3lUi1XbEEE6RKci/OshAehw6WXiQta+AZecWk8u1ZVUSQ2DqhVH59VT083mn8jD7VpziLD1EDU5BypbNjLOo6aui0NPHB7J6IRfCAvGTCbcYzD8+qpeeEPYkxnxG5I2lq2yflTmkHcNLjTyEnZSWSsgw/JGtcPj2kDf6nSgi/Jyn4M3t8pYl/zDSNLeTHMT7MRcsplDw7nk2+o1SdHSXM8DGGcjFGdVNwsVUfBbV3InzB4lShMj0u+LwA==
  template:
    metadata:
      creationTimestamp: null
      name: alertmanager-config
      namespace: monitoring
    type: Opaque
