---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: alertmanager-config
  namespace: monitoring
spec:
  encryptedData:
    alertmanager-config.yaml: AgAaSnEkttqJx5RNtrH0wgAltraFXtbxyyvQXfKMBwBqUzHQuMHiTeQN0Lp1vOV1C97rqYKdEPMU3KgKnQee/mAPaHsJWymMjpNvS0wJWiEzLb0DoX/bZGTy8OTU2lt+2lWOTugxcziwVOTeoBlsmQg8XIBO+LLEwgqFn9PIux7iYmQn4eRYGB4TqIXZgwn3InxLwom1RpMZNirzJjr8hvqterkUqJsWdmxiw9iu/VEK33iJmmijbOiAR5Ta28mPsxPCbU8e9wMl3TVMJ7a62V8SZJIGGlFfj6MY4BtJoLCCcBGy4HRkVadLFHfaNuusNvqiu+laQ+DiIX0MIyPOwUZgn4jzKEFZMJzrr+Y0NrKKdJpO60F0GzDggZ7w9cSAxVKx2vkXwVdVnkYe1i2ETvVuNlx5U2OMDxUOmND61bc3u0OwSI6qF/tGP5lZ2WUPnR0iAA/3PP18iF1JmHOn+l3sRB0u+vQAj6dqvOAp7N9PIQwwkYc2onhJ1wMZD3F6kLFArhO2stwQ4VPwHs7eVz2wK+ea1smaR/OIYDc00BCk7mrH+05KtECBgqo5Z+ajWDllUHH7Ygz4YPxOlI4GVn5A/lV+3iRtcxeoI+7WSV43VHhFewO6Yx3h8SqRCny2tvh7IP+buJltq5TRg7hFmFrb/H6bJ2nLTY44YjG1EJFgpzDO5icbU90jvV7jRlgqYs7t1Ed6a8vG4idQ788765VBtxL0KKTz2CsHwIuoxJSFxb8cAyjb5rUHT0fGEZmtT3eBxP1glmVvCvXWZ9XmjLU83MNB46IWD6v3YnboZSr+GDLtU4KsU0AHlP9kOgApVfB6WveNrIi+1Tfi3JkR2U7zn1FiFVPYiX7QLRHpdyf13h8RApykySy++vMD9bg1tvXocNy0O4Ftv0Og2+Jzsse1U4CZXsxdHJwnUTjhi63uasWryxCz5SCbXYdzytv9zM/cHHIKa3RFDm9KXm/0T0Sz/WKm9DKhaDpxhVrK5ACORQn2NlUTD457ZeXKu+DZ4t2IsQRCDIEwCvZ1miBM6gwlL0YDWw7d822jmFor5H/+XZjoiGyt13Bkj0JZJnFXoSNeuw3RmZ+BB+PCBF132KW9BD6FpEYKRpRtYl29j2tYTMN9mJYsQAMsbEkH06VZAYwW70p5kQCI8Zw4n9QrVraVl0ePc2S6M8d8OGNoX57xCaBLOTKYJxy9TPd0N4jmqkQmtwZ58A==
  template:
    metadata:
      creationTimestamp: null
      name: alertmanager-config
      namespace: monitoring
    type: Opaque
