---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: alertmanager-config
  namespace: monitoring
spec:
  encryptedData:
    alertmanager-config.yaml: AgBeUDVcBokkIMgsbP5rJi6iPntEGvBqzl8HEg73mDqDv7gNBmdX81vHsje0yKSkQnvz5iVsRqPfrZmqKcwfwF/RQCvzcv1NNwdWWTnCFdnTJTSJgo1gd5tLaEVOi/OP/EVYEzIOb8P6RGlx6znTd2fVM3NzCqTVfyUIuYnsWM+NOmNFF8nmWfm269+cFhlpgrqr/KpKtjT9D1/eS2luy5pv7uQzAn1WsSQZsSuqA9eX4RyTrGD465BQUXXYha5OlRFyJaZOUC02R0ekOk/AY4Cavv6LfXFgRcXqi+R3cTpnHJ2vIQGLyrxbDnVTNL3r1ChTTPQi3pf92nHiGqkDwHWCWRrRsez9DMA4aX2eCr4Lc2almTnch8Js6IoUtaZ2InnsQS2ACPg2x9rzZRsQZb+vBvFkzYiBXLyBdzktjPD2qHKqQhjvX4hpoO63+my1995olrMWUYsN7YLy1xMNurzhAuFDiEA6TZC1LymrXJM+7iGVnjMttUa/WlD7lGE167Tkbo18tf+DmdF2e1ZBhwMfITUiwXDJ1HpMUMgGHGY51RZP8BseNKZCRty20dw/pmNz+aBdAEbo6WqyPy/jeNvZJE4DZppvkq1MiKdrw42GQTaD61FCzVKNxeSdeWTyB5weXMVctnd6RHfeT9RARSCQg+jZCgjwocAkhPYJswzVqA7tMY7gP8xRsPMZTibEmBq+XoK0Y7+grgEesG9xOSrpAED/VflB37ybqvHOxSSbkUQ2zFRQfkbAunk1G/ynvjOTa9+T4sEC9mj3thqt5VhElSRPkJ3idvDNPxTKSFpAuuTNo/wbFWLB9tbQYiiMNMpQCHDDuwJnRKnxB+eU88eX9LWzC4yrDvOPURDCEyTrdUWLNitoebkqIklscbL/ULvKm5LFSugYyVsMxupo4FsfEA5vk08AgRfTNeXRVMiXJkPLTodxhTuk9KGN7DV6G2argQNVtmtGwjWoZSxjzTQ6gL3PYhPyeW0XpT3XN3R+jLD/E5sXR/LaeAciA0G+bqXqydD3UxDzhMO1rZWpPEg4FPOAbGUYU8kzTPA3EQMQWz2ISvpxkHDFKvHs0LbTlnuZv7+NGl/15rnTqrofOWPYE8S/PItA62TDUR/mkYCeAQuAhcKwMkzMNbQTJHEbiiUj2kfVR6M5bae6E6bU7POO2mCZgX3HdGqtMTp57Q86Nm56K4DZQwNK+bZrfswqLJL2Plsd7ze/lPisOb+Imy80p2JagUDsdEI=
  template:
    metadata:
      creationTimestamp: null
      name: alertmanager-config
      namespace: monitoring
    type: Opaque
