---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: alertmanager-config
  namespace: monitoring
spec:
  encryptedData:
    alertmanager-config.yaml: AgBU7Ei+WSnnMZY7mPXqK1UgWbohtkQy0PcqEUciECXqsliV2Nskh2VfMAPV0LfnYXueUfvQP8ShBYwBSFT2M+Hja8pW+Ma1VR8Bf309olzDy3II7jF6SYxd9fI9iORWONyzEV68/UZCTE/bgZFHK0BC07h5uN0GQ9FuZotbsiENlAkFhIOCwAhHV67srfYfgJABP8IG7hw6fxV3cmjKjpKO4AkrdRFoxlGjC/i+6w9MS7BMThXz8I1/+4VN20zapy7Qf3c/5skM+8XTdD3P4vlxCb3qpDb2oOu39nbxastN1H3Vld0rOdW41z84exDR13kVTGXHJbfYQ88PEI4DySCPKs6D9/A8tF0mrCBx43/Ap3Ff5hMXswvcN+c0F/77GKBsBdsUAl4ZMDr6wCNi954tts73C/+JU5XqMwEvAYfSv5dabAHq+nNbRNthy0R9YNWHXwKMGxRQsfauW9I1Mo8ArVkE+WKBd7rlAf0uL3gsYBAybOIogbP6NZgcdXjnXe6D+AXIuJokCBf4MwhmBY5T77MpX5q/S8NEJyVzKfQQ1PTNMmPcrgxDNX6a+0InZhbhnYRVaa4Fbf1sh/jDqi8W0+qUyLfdQOox/gscZ5+HL9QxaJdM172aL6wV+pphTi6a6ivnDIi3XLtBifNa0EIH5MOXS586VKU+9nZag7ugk7qq/CDM28paa76mBoRqO/NMJevEQ2yLmteVyZ+mHeMqHbj6r8TH6seCXYWUhCbuMfaGGGVw4YJNXGkA7tZ58dpFLHCQKKH0wj7uK/W4yCnqC/Zql/aK3Cw48vK2sFFPRnc/7z56vVXYet+HAuIE0S9ckC5sjrCTOw3yii0zrdFXcaSVPG0iB7vol31vHtnInss8grimfSRyoqyjz6hkIc4nEi5g43N0v4hVPaZStIQsWSU+fOULwxYEKR8YMQcneI9cGuDN+Mfvs7RN/Un0zWfNTbEZFQYwva5XvaxDpfN13BtLEpzua9JyUhHoBYJ9NNCirEIHpS9q8VQDkhYizSCewE01uRxOVaKZI6SILHKqXWJrfkeC76WoBfCIWEYPosTsL5HGuxuCZXgAQPW5oFE/1CIsB/PJ0NO/fnruraVXB4euRaqzwnkzUwvNETexvkplOyiVzKYd9P2mQUlfHKoZVd84UE9AUBhdl98HypaXhUjr6800Bg+6GzpIiscBDRaCoFYBGlAPl1CD+tB5aOd01R28qw==
  template:
    metadata:
      creationTimestamp: null
      name: alertmanager-config
      namespace: monitoring
    type: Opaque
