---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: alertmanager-config
  namespace: monitoring
spec:
  encryptedData:
    alertmanager-config.yaml: AgAsErMkA9eraD/3pTgJeeTpvA2CapzaHAWKJC5oSFo48sxIaWCJ062lC+OLZ/DsNSdxYLaUWmKhIf63A33E8J8ldbFQ/gRCT8dwzUx2gz2QG6/1+6i/RyHWIBs7Iv5YfV7QXbeWwdGEGxcyij9hIhOK7JT077bu6g0GCksy5CUjTZfp0tXxPVV7RsOL6Rm7y9HfPUGFcG6XBgppGCihliFDUOAcq+3xKfEQNDpPxxBHTdhahvlr4zJaV4JIEgXp+z30py0lTQHb0OgF2Dkn1PieuCz32jwJQ1TnB2WgcycRTj7h9UaNUdPdzNqVWqkHa40eOawiKc+O37F1iZXjyj6fsnCo/dXAGiS3Bj1TITId4/fR/2g0gJfaanzEHhChN3NbqjskeMbOzet9FAC/77hUst32Y3ZW/jRUEDyS6SrObbwkKcuSK4me649Qv7fMPKig7iEbCNskhIRZr7pCUF1IaYqda1880ECAJ5Saickz1Gnp07Dk0/X4gxRD/2pLtWzg212bvx7HA9WH6/oiQw/mwS+D7N07L3/Zhexi2k6/KuuWwX7KAS/GyIN2EAhwLIfLPACwqHzETLirxze63Li2iZeEogQM66CiPwtOcul8yB9O8KX/PYmRVR0864ONBn8ahrGoXj+QPvlaY73Fm0iFN3Sw/fVBauUQ4u65J1Oe6bqbRTzaKsZ6yCMP6AOBMjVeTaslU8ISESyuTeSHaGEqzxQ7s99YBDTtQUT3dXa+rjmv43huTKvaCewT3N6z++bdPZsc601JYgPWqeUKdGmJzuHc5k1cfcb8raUuLqWF/n1xt8IVYNuq3fEPEnOHzGUPZJBANXqNSvXrJEKaJ80tXiClUJPCUoEj5bEI4TgUaUCGr6PmcTaNWepiAqDYQew32fHH9IIuXbVIswkrbjkhq38Bgexp0ZBkdMO3+4xTOc+npCoSX8ZoRf1qxaJFAc7jDlmVK7usdrD06S66RbUidXjsn4q6NuzjFJpuJCiG+YK4P7pXlrLAIkTIxNrWKJSo+bcTWdZzTLqGdXqNKhWx9GOATDitosFqQWMvcwrlgd25Xdi24ZICh4VZ04G9XLh9zVurN8wqu3YQAp2tvoXH8vhjqCcC5O7tmPLrV8deOnEsGYm/ecBovZ6uPfMfdEJ4U4wSVYPyG6ntucWJFwg0LCxR88S5qyWAdVdfg1IMDq9gF+9Z9VrtrNB27FvhLwhiWlFRsWqxNF/DB9UFRSJkgD5ZkosokRLlIsGxuFVd3iUXGET1wUBIA1KrMAkIzgj2UOTxSl2wLgzz6L16SgdEjunu9rzdBYyn7VWVkG5onqZ7f570VZzfGKKsYx32eSJZNQkJUXldkJONM0G9E5lXmWCXQYv7SFv4Sq7OCsDYYuJg5cEr4ox5bDYY/GKA+c1nMSa2Yo1BLyaS1R+nvVfDhMxXgy2GwwUYPQvcOIUPFN+A6h/J64Zneky2Sm49bQ==
  template:
    metadata:
      creationTimestamp: null
      name: alertmanager-config
      namespace: monitoring
    type: Opaque
