---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: alertmanager-config
  namespace: monitoring
spec:
  encryptedData:
    alertmanager-config.yaml: AgBeFhkq7O7qHk8ZLqdOAbysx0q2GeAXDNYBxRXTCsBNqmkerm80ZBzSFNECWEX1/FZmOehA5s1QfmXwNOW/NCfax/oHlu7RS8ir1eL/bjA+5E/vEutqG63m3zGS+nJUihy+XxeDABXsn3SV5AkkUDf/WJITnwbRinWXXL65vTmFnz1CHTgmQpPzMAa3IcVsSNf1N3P3+s9ZmMhpV67z6gx9Tg2Ct4jYuNhxBglFCyDILG6r5cs5m6uoIc80Jgnnpqc1WhhuHIoJi2UWqCcncvEXXVla0RnD04SDjCeNLQQfQ2973oMkOULRze1hWBKwSB5D26qRjwwIt63G/548Qh2yI0m0r6S5qRITrEZ0fAv+tQJU14ASFAb3YMftFdwNmANrNfmnUykF0Aq0zxRbSJNkwgyCUorJE4ZYgjpOUAGdql19WmN7ZB/RZvRZrFlGaWPmtKAts0Mh5zvmdrjDqb7zXFmJTGohYzYA+mN+sOl3jjE+I2GwR7/WF+tptWBrBfuULPuq3a0CSwZTVBLMy8f+w7Y54As6GxfNcMMPm/qdOsq74MXKtJh2DzdPtwENXRIQHulGrXim4kFKajLqxFm95Wzdfj14vdjjrkMcKExiO/Ux0GMeUbryAeBLuXiqCd4iyXBogxd5QaPvDAxUwoFTQ8T8AYwabD1MugaFTERkXqcKAodVBD6GR0Qha5jFOOhirAeCzYX4Hi60ZKb9tlQFpBHUPpa+CGGfQemIhT+MOPoRM5zREGBuYxa+SuZW+KUNdDXjtELrFck1J2h9KxpKHg54jTCJBB1RhDzVyzKVMW+nrvG7/9WyBlZA9knwLbAvMouVhML+dkE/gRgkBjo17f+OtWgAf94Ji8gGyP+FQxsNNY9YyqEGmHucATb7QNvrqA4NtlPpTRAIrTFd2h2Ye6UJprR1YUm60dRQrgx+WKP/jNZBdfttw6EEF1PcrmUxj3WykAm4QsVOlB/ppaiyggdUl8y7WfWwIr3TMZrjz/AAv6v5XNGm+BITFYqfn9wKpiCbAqO0x4XJX2WqS0T7ZIBRPO5LvWogdIsU3BkGa13ROqJi84q7iliewc188w+IhFVmR2wa4xDW1p32YITOvY2K8pV4nBKd6IBtGamUxjNCqOpauyYU/akC48UmUJ9eyEBUwhyYyQe4gcp+QNudSUu2iEEkNfv63LDbPMo0LrGa55HLXsVrIBkS93y1IIzI3QD1eONEMcXtEoROYXNlLX8mxax71FY=
  template:
    metadata:
      creationTimestamp: null
      name: alertmanager-config
      namespace: monitoring
    type: Opaque
