---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: alertmanager-config
  namespace: monitoring
spec:
  encryptedData:
    alertmanager-config.yaml: AgAuG9m7C+2gbPmA91ZnSuKiGAaILaFMvK8YUXah3mKl3aHi0Qud2FWmw3hivf1yTM0zzqsUVb9/7525ZGZk101FtHZ8Wf3TKoIMnxG1wfYMNMOxcAQb8BDDXKojR0ROR/VqqD8zafPMiZ2fVwW/qlOWsSeOxvRu7I5QkMNhOQStwXDmjQWIG+frdGJksOu/p2eYxZseIA2Jq11C4vO1LxBwNewkUNCokuWVnDRsvDgD0QO9Iyx3BJDuJdutuWGokGzxcYlZJdASAH8ClPy80K/nRNQxjvwCYhOwnojoXiXwOliQJsYTrPobGTb2j5i+1kpAC0bJyk8X+5CEn/bWy/b5XaWH3+3f/cBbs52XKSQkLMdBqeDMECgoNsVwuW5NZITVQcI7m1YY4xqGk2aAkpY5j7KDmd3eNu3rXXREExKmKheueggoX214y7pHwbTAZTVGO2eqE0SVkRxDoLulvWGxv9xl0KOw+SfIaic24P77vtbfG+YXkhXm0pgRbi13+zypnboaaVvQJDG+4CoSkbBHHtPnLE1QE7uPGBl1SlLPg6TiAHvrDZiPMcVu4C07Ulz8KMZWktT9v1B+rply/06F+jHn5m9Ok5f65hM/Am/0SfjwgIgbv7mYIuvPbAoph4QNyZ/2BL2NOB5wSPRpiOwmoKyEjSdazqbY/kLAb0aWaygXJakzSatrDzbXpQ4RDN+5Iw5MC49lFPYYHwG82pcnijNaPCu5K0ljNtXMc26Ttn+Kz9+8vHgfVk5QFN5A0U+JSZi0zj4gAl56zSHclJJu7ZV3qvwRfn6VeYmU3qVpt1z+qH4gExjPAra0rqvWs4VVU/YARFuDAXz81adQ21Td6XKCyER+VX4k7ffKU2+tuxO3zh6jCkfPlgMIwF/tAyHfGPkMPHFNn9xi4Eale1tuCdhQGd3bWJvVz96HiiAPuObGK92N1WlPXosam2oUlaNasu/B6M3gB7Xf1E24nh5Lg4IbuS8nFXnu9fnICOY4RkUvuaA6gric3J7eDGTpdONnFp7aFQF9wbCZpLmEtQRFWRi7xJCBVTAwrhuBe5fOWOnVVaNVxxZoPbO1WrYztSPVd6kQX0GMDobEuB+PCDgsUtkgDhnB69Li9N7PXyFryGQL3tz7EFtA0OiXDqvbSxgx0p9VYPny+Zj/uVNW4a55YVXlT91vZ/8HYFexMzP4p2/0Go0VZGpom+wqDheugw2oZRapw7LZnZr7SlR/tqWRrRxpDldAyGZpWv5vauU7Q7tpIaC1rao7pf1tUYUPbZw+1q4IM/nYJXtSyOqik0Dj7ALx2D5MJ+Z6e96UV87vXMc3Xpjdz2+ilFJyKyad/1f+II3BpZR7xnUO9710wtCmqQeiwTGjaodSU9FjE2TJ7q0cd0/IGu8+i2dKBdW6kLfrdzIoq1C6BilBEKwtoYE5Sm1x+EWJrQN/F9lRYTd2jnV5e1ADeSeeEKLdp39cM7VeFJzSbvAySdWNkziHH+dmg/C6FuqrrOLo+OoXUr3Apm5LDQs+Y18R0RBN3VvoRoHS+7T4pBc5c/BEbvqzp7L4Fk5eCOVUnIYjrLZy2kR2enWHMgmTM1XVDR7IU1g=
  template:
    metadata:
      creationTimestamp: null
      name: alertmanager-config
      namespace: monitoring
    type: Opaque
