apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-app
spec:
  destination:
    namespace: argo-apps
    server: https://kubernetes.default.svc
  source:
    path: argo-apps
    repoURL: https://github.com/fedos1993/argo-cd
    targetRevision: HEAD
    directory:
      recurse: true
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
