apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jenkins
spec:
  destination:
    namespace: ci-cd
    server: https://kubernetes.default.svc
  source:
    repoURL: https://fedos1993.github.io/helm-repo
    targetRevision: 0.3.0
    chart: jenkins
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
