apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jenkins
  namespace: argocd
spec:
  project: default
  destination:
    namespace: ci-cd
    server: https://kubernetes.default.svc
  source:
    chart: jenkins
    repoURL: https://fedos1993.github.io/helm-repo
    targetRevision: 0.3.0
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
