apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-config
  namespace: monitoring
type: Opaque
stringData:
  alertmanager-config.yaml: |
    global:
      resolve_timeout: 5m
    route:
      receiver: "slack"
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 1h
    receivers:
      - name: "slack"
        slack_configs:
          - send_resolved: true
            channel: "@Денис Федосевич"
            username: "Alertmanager"
            icon_emoji: ":warning:"
            api_url: "https://hooks.slack.com/services/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"
